name: FlyingCreeper

author: AndyHunt, Learn to Program with Minecraft Plugins
website: http://pragprog.com/book/ahmine

main: flyingcreeper.FlyingCreeper

commands:
    flyingcreeper:
        description: Pure. Terror.

version: 0.1

