name: BackCmdSave

author: AndyHunt, Learn to Program with Minecraft Plugins
website: http://pragprog.com/book/ahmine

main: backcmdsave.BackCmdSave

commands:
    back:
        description: Teleport back to the last teleport target
        usage: back

version: 0.1
