name: Stuck

author: AndyHunt, Learn to Program with Minecraft Plugins
website: http://pragprog.com/book/ahmine

main: stuck.Stuck

commands:
    stuck:
        description: "Trap a player in cage of blocks"

version: 0.1
