name: SkyCmd

author: AndyHunt, Learn to Program with Minecraft Plugins
website: http://pragprog.com/book/ahmine

main: skycmd.SkyCmd

commands:
    sky:
        description: Fling nearby creepers into the air

version: 0.1
