name: MySimple

author: AndyHunt, Learn to Program with Minecraft Plugins
website: http://pragprog.com/book/ahmine

main: mysimple.MySimple

commands:
    mysimple:
        description: Simple first plugin

version: 0.1

