name: ListPlay

author: AndyHunt, Learn to Program with Minecraft Plugins
website: http://pragprog.com/book/ahmine

main: listplay.ListPlay

commands:
    listplay:
        description: List demo

version: 0.1

